"""Isolated single-disturbance-event DMC DV-information experiment.

This script deliberately compares only ``DMC-without-DV`` and ``DMC-DV hold``.
It reuses the actual scenario-7 event definitions generated by the existing
benchmark, shifts their onset to 180 min, and never supplies future true DV
values to the controller.  The source benchmark itself is not modified.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import numpy as np
import pandas as pd

import run_robust_hrsg_simulation as base


ROOT = Path(__file__).resolve().parents[1]
SOURCE_OUT = ROOT / "outputs" / "offline_simulation"
OUT = ROOT / "outputs" / "isolated_disturbance_events"
OUT.mkdir(parents=True, exist_ok=True)

WITHOUT = "DMC-without-DV"
HOLD = "DMC-DV hold"
CASES = {
    "A_condensate_flow_only": {"label": "Condensate-flow-only", "kind": "condensate"},
    "B_makeup_flow_only": {"label": "Makeup-flow-only", "kind": "makeup"},
    "C_unmeasured_only": {"label": "Unmeasured-disturbance-only", "kind": "unmeasured"},
}
T = 360
T0 = 180
WINDOW_START, WINDOW_END = T0 - 20, T0 + 100
EARLY_END = T0 + 5
RECOVERY_BAND = 0.005
RECOVERY_HOLD_MIN = 10
TEST_IDS = tuple(range(1, 31))


def _stage_vector_from_seed(seed: int, T: int, mismatch: bool) -> np.ndarray:
    """Reproduce the saved generator's scenario-specific coloured-event vector.

    The original event JSON saves the vector norm but not its three components.
    Replaying the unchanged generator's random-number consumption recovers the
    exact vector, rather than inventing an approximation.
    """
    rng = np.random.default_rng(seed)
    if mismatch:
        rng.uniform(-0.15, 0.15, base.KM.shape)
        rng.uniform(-0.20, 0.20, base.TAUM.shape)
        rng.choice(np.array([-2, -1, 0, 1, 2]), base.THETAM.shape)
    for _j in range(base.ND):
        for _k in range(1, T):
            rng.normal(0, 0.004)
    rng.choice(np.arange(70, max(71, T - 45)), size=3, replace=False)
    for _ in range(3):
        rng.choice([-1, 1])
        rng.uniform(0.08, 0.25)  # bounds do not alter the random draw consumed
        rng.choice(["step", "ramp", "pulse"])
        rng.integers(25, 55)
    rng.normal(0, base.W_STD * 0.6)
    eta_std = base.W_STD * np.sqrt(1 - base.AR ** 2)
    for _k in range(1, T):
        rng.normal(0, eta_std)
    rng.integers(150, max(151, T - 60))
    rng.integers(20, 50)
    return rng.normal([0.006, 0.006, 0.010], [0.002, 0.002, 0.003])


def _source_events() -> Tuple[base.Scenario, Dict[str, Dict], np.ndarray]:
    """Load scenario 7 by its original seed and audit its saved event metadata."""
    events = json.loads((SOURCE_OUT / "scenario_events.json").read_text(encoding="utf-8"))
    stored = next(x for x in events if x["scenario_id"] == 7)
    scn = base.create_scenario(7, int(stored["random_seed"]), T, True, True, "source scenario 7")
    by_name: Dict[str, Dict] = {}
    for event in scn.events:
        if event["dv"] == "Cond_Flow" and event["kind"] == "ramp" and event["duration_min"] == 38:
            by_name["condensate"] = event
        elif event["dv"] == "Makeup_Flow" and event["kind"] == "pulse" and event["duration_min"] == 28:
            by_name["makeup"] = event
        elif event["dv"] == "unmeasured_colored_disturbance" and event["duration_min"] == 26:
            by_name["unmeasured"] = event
    if set(by_name) != {"condensate", "makeup", "unmeasured"}:
        raise RuntimeError("Could not recover all three requested scenario-7 event templates")
    stage = _stage_vector_from_seed(scn.seed, T, True)
    if not np.isclose(np.linalg.norm(stage), by_name["unmeasured"]["amplitude"], rtol=0, atol=1e-14):
        raise RuntimeError("Scenario-7 coloured-event vector failed exact norm audit")
    return scn, by_name, stage


def _shifted_dv_template(event: Dict) -> np.ndarray:
    shifted = dict(event)
    shifted["start_min"] = T0
    arr = np.zeros((T, base.ND))
    base.apply_event(arr, shifted)
    return arr


def _background_w(scn: base.Scenario) -> np.ndarray:
    """Remove only its deterministic coloured event, retaining the AR(1) path."""
    event = next(e for e in scn.events if e["dv"] == "unmeasured_colored_disturbance")
    stage = _stage_vector_from_seed(scn.seed, scn.T, scn.mismatch)
    result = scn.w.copy()
    result[event["start_min"] : event["start_min"] + event["duration_min"]] -= stage
    return result


def make_isolated_scenario(case: str, scenario_id: int, level: str, templates: Dict[str, Dict], source_stage: np.ndarray) -> base.Scenario:
    """Create a matched clean or stochastic single-event scenario."""
    clean = level == "clean"
    seed = base.MASTER_SEED + 7 if clean else base.MASTER_SEED + scenario_id
    original = base.create_scenario(
        7 if clean else scenario_id, seed, T, not clean, not clean,
        "clean deterministic demonstration" if clean else "matched stochastic isolated event",
    )
    # All measured-DV background trajectories are removed.  Only the selected
    # scenario-7 waveform is applied; measurement-noise draws remain untouched.
    dv = np.zeros((T, base.ND))
    w = np.zeros((T, base.NY)) if clean else _background_w(original)
    event_records: List[Dict] = []
    kind = CASES[case]["kind"]
    if kind in ("condensate", "makeup"):
        dv += _shifted_dv_template(templates[kind])
        rec = dict(templates[kind]); rec["start_min"] = T0; event_records.append(rec)
    else:
        event = templates["unmeasured"]
        w[T0 : T0 + event["duration_min"]] += source_stage
        rec = dict(event); rec["start_min"] = T0; event_records.append(rec)
    return base.Scenario(
        scenario_id, seed, T, original.Kp.copy(), original.thetap.copy(), original.taup.copy(),
        dv, original.dv_meas_noise.copy(), w, original.y_noise.copy(), event_records,
        original.mismatch, original.label,
    )


def run_controller(scn: base.Scenario, controller: str, pidpars: Dict[str, float], case: str, level: str) -> pd.DataFrame:
    plant = base.FOPDTPlant(scn.Kp, scn.thetap, scn.taup)
    dmc = base.DMCController("hold", base.PIDController(pidpars))
    reference_dv = np.zeros(base.ND)
    rows: List[Dict] = []
    for k in range(scn.T):
        ytrue = plant.output() + scn.w[k]
        ymeas = ytrue + scn.y_noise[k]
        dtrue = scn.dv_true[k]
        dmeas = dtrue + scn.dv_meas_noise[k]
        dctrl = reference_dv if controller == WITHOUT else dmeas
        u, status, _pred, active, dhat = dmc.step(ymeas, dctrl)
        row: Dict = {
            "level": level, "case": case, "scenario_id": scn.scenario_id, "random_seed": scn.seed,
            "time": k, "time_min": k, "controller": controller,
            "controller_DV_mode": "nominal_zero" if controller == WITHOUT else "measured_DV_hold",
            "DMC_active": int(active), "QP_success": int(dmc.last_qp_feasible),
            "QP_attempted": int(dmc.last_qp_attempted), "constraint_rate_active": int(status["rate"]),
            "constraint_amplitude_active": int(status["amp"]), "constraint_cv_active": int(status["cv"]),
        }
        for i, name in enumerate(base.CV_NAMES):
            row[f"{name}_true"] = ytrue[i]
            row[f"{name}_measured"] = ymeas[i]
            row[f"{name}_unmeasured_dist"] = scn.w[k, i]
        for j, name in enumerate(base.MV_NAMES):
            row[name] = u[j]
        for j, name in enumerate(base.DV_NAMES):
            row[f"{name}_true"] = dtrue[j]
            row[f"{name}_measured"] = dmeas[j]
            row[f"{name}_controller_input"] = dctrl[j]
            row[f"{name}_predicted_1step"] = dhat[0, j]
        rows.append(row)
        # This is the second required information boundary: no-DV advances its
        # internal model with nominal zero, while hold advances with d_meas.
        dmc.advance(u, dctrl)
        plant.update(u, dtrue)
    frame = pd.DataFrame(rows)
    for mv in base.MV_NAMES:
        frame[f"d{mv}"] = frame[mv].diff().fillna(frame[mv])
    return frame


def _recovery_time(e: np.ndarray, time: np.ndarray) -> float:
    post = np.where(time >= T0)[0]
    for pos in post:
        end = pos + RECOVERY_HOLD_MIN
        if end <= len(e) and np.all(np.abs(e[pos:end]) <= RECOVERY_BAND):
            return float(time[pos] - T0)
    return np.nan


def _onset(du: np.ndarray, time: np.ndarray) -> float:
    threshold = 0.10 * float(np.max(np.abs(base.DUMAX)))
    choices = np.where((time >= T0) & (np.abs(du) >= threshold))[0]
    return float(time[choices[0]] - T0) if len(choices) else np.nan


def event_metrics(frame: pd.DataFrame) -> Dict:
    time = frame.time_min.to_numpy()
    event_mask = (time >= WINDOW_START) & (time <= WINDOW_END)
    early_mask = (time >= T0) & (time <= EARLY_END)
    values: Dict = {
        "case": frame.case.iloc[0], "scenario_id": int(frame.scenario_id.iloc[0]),
        "controller": frame.controller.iloc[0], "level": frame.level.iloc[0],
    }
    for i, cv in enumerate(("HP_pH", "MP_pH")):
        error = frame[f"{cv}_true"].to_numpy() - base.YSP[i]
        display = "HP" if cv == "HP_pH" else "IP"
        values[f"{display}_full_IAE"] = float(np.sum(np.abs(error)) * base.TS)
        values[f"{display}_full_RMSE"] = float(np.sqrt(np.mean(error ** 2)))
        values[f"{display}_event_IAE"] = float(np.sum(np.abs(error[event_mask])) * base.TS)
        values[f"{display}_peak_deviation"] = float(np.max(np.abs(error[event_mask])))
        values[f"{display}_recovery_time"] = _recovery_time(error, time)
    values["Total_event_pH_IAE"] = values["HP_event_IAE"] + values["IP_event_IAE"]
    values["Total_full_pH_IAE"] = values["HP_full_IAE"] + values["IP_full_IAE"]
    for mv in base.MV_NAMES:
        short = "MV1" if mv == base.MV_NAMES[0] else "MV2"
        du = frame[f"d{mv}"].to_numpy()
        values[f"{short}_TV_event"] = float(np.sum(np.abs(du[event_mask])))
        values[f"Early_{short}_TV"] = float(np.sum(np.abs(du[early_mask])))
        values[f"max_abs_d{short.lower()}"] = float(np.max(np.abs(du[event_mask])))
        values[f"{short}_response_onset_min"] = _onset(du, time)
    values["Total_MV_TV_event"] = values["MV1_TV_event"] + values["MV2_TV_event"]
    values["Early_Total_MV_TV"] = values["Early_MV1_TV"] + values["Early_MV2_TV"]
    values["QP_failures"] = int(np.sum(frame.QP_success.to_numpy() == 0))
    values["DMC_active_ratio"] = float(frame.DMC_active.mean())
    return values


def paired_statistics(metrics: pd.DataFrame) -> pd.DataFrame:
    metric_columns = [
        "HP_full_IAE", "IP_full_IAE", "HP_full_RMSE", "IP_full_RMSE", "Total_full_pH_IAE",
        "HP_event_IAE", "IP_event_IAE", "Total_event_pH_IAE", "HP_peak_deviation", "IP_peak_deviation",
        "HP_recovery_time", "IP_recovery_time", "Total_MV_TV_event", "MV1_TV_event", "MV2_TV_event",
        "Early_Total_MV_TV", "Early_MV1_TV", "Early_MV2_TV",
    ]
    rng = np.random.default_rng(base.MASTER_SEED + 941)
    rows = []
    for case, group in metrics.groupby("case"):
        piv = group.pivot(index="scenario_id", columns="controller", values=metric_columns)
        for metric in metric_columns:
            x = piv[(metric, WITHOUT)].to_numpy(float)
            y = piv[(metric, HOLD)].to_numpy(float)
            valid = np.isfinite(x) & np.isfinite(y)
            x, y = x[valid], y[valid]
            if not len(x):
                continue
            delta = y - x
            boot = np.mean(delta[rng.integers(0, len(delta), size=(10000, len(delta)))], axis=1)
            rows.append({
                "case": case, "metric": metric, "n_paired": len(delta),
                "mean_difference_hold_minus_withoutDV": float(np.mean(delta)),
                "relative_change_percent": float((np.mean(y) - np.mean(x)) / np.mean(x) * 100) if abs(np.mean(x)) > 1e-12 else np.nan,
                "bootstrap_CI_lower": float(np.quantile(boot, .025)), "bootstrap_CI_upper": float(np.quantile(boot, .975)),
                "d_z": float(np.mean(delta) / np.std(delta, ddof=1)) if len(delta) > 1 and np.std(delta, ddof=1) > 1e-12 else np.nan,
            })
    return pd.DataFrame(rows)


def summary_table(metrics: pd.DataFrame) -> pd.DataFrame:
    numeric = [c for c in metrics.columns if c not in ("case", "scenario_id", "controller", "level")]
    rows = []
    for (case, controller), group in metrics.groupby(["case", "controller"]):
        row = {"case": case, "controller": controller, "n": len(group)}
        for col in numeric:
            vals = group[col].to_numpy(float)
            row[f"{col}_mean"] = float(np.nanmean(vals)) if np.isfinite(vals).any() else np.nan
            row[f"{col}_SD"] = float(np.nanstd(vals, ddof=1)) if np.isfinite(vals).sum() > 1 else np.nan
            if "recovery_time" in col:
                row[f"{col}_observed_n"] = int(np.isfinite(vals).sum())
        rows.append(row)
    return pd.DataFrame(rows)


def sanity_checks(timeseries: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for (level, case, controller, sid), g in timeseries.groupby(["level", "case", "controller", "scenario_id"]):
        true_dv = np.column_stack([g[f"{n}_true"].to_numpy() for n in base.DV_NAMES])
        has_cond = bool(np.any(np.abs(true_dv[:, 3]) > 0))
        has_makeup = bool(np.any(np.abs(true_dv[:, 4]) > 0))
        other_zero = bool(np.allclose(true_dv[:, :3], 0) and (case != "A_condensate_flow_only" or np.allclose(true_dv[:, 4], 0)) and (case != "B_makeup_flow_only" or np.allclose(true_dv[:, 3], 0)))
        has_unmeasured = bool(np.any(np.abs(g[[f"{n}_unmeasured_dist" for n in base.CV_NAMES]].to_numpy()) > 0))
        control_dv = np.column_stack([g[f"{n}_controller_input"].to_numpy() for n in base.DV_NAMES])
        rows.append({"level": level, "case": case, "controller": controller, "scenario_id": sid,
                     "condensate_event_present": has_cond, "makeup_event_present": has_makeup,
                     "other_measured_DV_true_zero": other_zero,
                     "unmeasured_disturbance_present": has_unmeasured,
                     "without_DV_controller_input_zero": bool(np.allclose(control_dv, 0)) if controller == WITHOUT else True,
                     "hold_controller_uses_measured_DV": bool(np.allclose(control_dv, np.column_stack([g[f"{n}_measured"].to_numpy() for n in base.DV_NAMES]))) if controller == HOLD else True})
    checks = pd.DataFrame(rows)
    # Deterministic event assertions only; stochastic background is allowed in level 2.
    clean = checks[checks.level == "clean"]
    if not clean[(clean.case == "A_condensate_flow_only")].condensate_event_present.all(): raise RuntimeError("Case A check failed")
    if not clean[(clean.case == "B_makeup_flow_only")].makeup_event_present.all(): raise RuntimeError("Case B check failed")
    if clean[(clean.case == "C_unmeasured_only")][["condensate_event_present", "makeup_event_present"]].any().any(): raise RuntimeError("Case C check failed")
    if not checks.without_DV_controller_input_zero.all() or not checks.hold_controller_uses_measured_DV.all(): raise RuntimeError("Controller DV-path check failed")
    return checks


def pairing_audit(timeseries: pd.DataFrame) -> pd.DataFrame:
    """Verify controller-exogenous paths are exactly paired by case/scenario."""
    rows = []
    for (level, case, sid), group in timeseries.groupby(["level", "case", "scenario_id"]):
        a = group[group.controller == WITHOUT].sort_values("time_min")
        b = group[group.controller == HOLD].sort_values("time_min")
        if len(a) != T or len(b) != T:
            raise RuntimeError(f"Incomplete paired trajectory: {level}, {case}, {sid}")
        diffs = []
        for name in base.DV_NAMES:
            diffs.extend([
                np.max(np.abs(a[f"{name}_true"].to_numpy() - b[f"{name}_true"].to_numpy())),
                np.max(np.abs(a[f"{name}_measured"].to_numpy() - b[f"{name}_measured"].to_numpy())),
            ])
        for name in base.CV_NAMES:
            diffs.extend([
                np.max(np.abs(a[f"{name}_unmeasured_dist"].to_numpy() - b[f"{name}_unmeasured_dist"].to_numpy())),
                # Measured-minus-true is the stored CV measurement-noise path.
                np.max(np.abs((a[f"{name}_measured"] - a[f"{name}_true"]).to_numpy() - (b[f"{name}_measured"] - b[f"{name}_true"]).to_numpy())),
            ])
        max_difference = float(max(diffs))
        rows.append({"level": level, "case": case, "scenario_id": sid,
                     "same_seed": bool(a.random_seed.iloc[0] == b.random_seed.iloc[0]),
                     "max_abs_exogenous_trace_difference": max_difference,
                     "audit_pass": bool(max_difference < 1e-14 and a.random_seed.iloc[0] == b.random_seed.iloc[0])})
    audit = pd.DataFrame(rows)
    if not audit.audit_pass.all():
        raise RuntimeError("Controller pairs do not share identical exogenous paths")
    return audit


def plot_response(clean: pd.DataFrame, filename_stem: str = "isolated_DV_event_response") -> None:
    plt.rcParams.update({"font.size": 8, "font.family": "Arial", "axes.spines.top": False, "axes.spines.right": False})
    fig, axes = plt.subplots(3, 3, figsize=(10.4, 6.7), sharex=True)
    without_color = "#555555"
    control_legend = [
        Line2D([0], [0], color=without_color, lw=1.2, label="gray: DMC-without-DV"),
        Line2D([0], [0], color="#D55E00", lw=1.2, label="DMC-DV hold"),
    ]
    ph_legend = [
        Line2D([0], [0], color=without_color, lw=1.0, ls="-", label="DMC-without-DV - HP pH"),
        Line2D([0], [0], color=without_color, lw=1.0, ls="--", label="DMC-without-DV - IP pH"),
        Line2D([0], [0], color="#D55E00", lw=1.0, ls="-", label="DMC-DV hold - HP pH"),
        Line2D([0], [0], color="#D55E00", lw=1.0, ls="--", label="DMC-DV hold - IP pH"),
    ]
    command_legend = [
        Line2D([0], [0], color=without_color, lw=1.0, ls="-", label="DMC-without-DV - u1"),
        Line2D([0], [0], color=without_color, lw=1.0, ls="--", label="DMC-without-DV - u2"),
        Line2D([0], [0], color="#D55E00", lw=1.0, ls="-", label="DMC-DV hold - u1"),
        Line2D([0], [0], color="#D55E00", lw=1.0, ls="--", label="DMC-DV hold - u2"),
    ]
    dv_legend = [
        Line2D([0], [0], color="#222222", lw=1.1, label="True DV"),
        Line2D([0], [0], color="#0072B2", lw=.9, ls="--", label="Measured DV"),
    ]
    unmeasured_legend = [
        Line2D([0], [0], color="#0072B2", lw=.9, label="HP pH disturbance"),
        Line2D([0], [0], color="#D55E00", lw=.9, label="IP pH disturbance"),
        Line2D([0], [0], color="#009E73", lw=.9, label="Conductivity disturbance"),
    ]
    for col, case in enumerate(CASES):
        g = clean[clean.case == case]
        hold, without = g[g.controller == HOLD], g[g.controller == WITHOUT]
        ax = axes[0, col]
        if case == "C_unmeasured_only":
            for cv, label, color in (("HP_pH", "HP pH disturbance", "#0072B2"),
                                     ("MP_pH", "IP pH disturbance", "#D55E00"),
                                     ("COND_kappa", "Conductivity disturbance", "#009E73")):
                ax.plot(hold.time_min, hold[f"{cv}_unmeasured_dist"], color=color, lw=.9, label=label)
            ax.set_ylabel("Unmeasured disturbance")
        else:
            dv = "Cond_Flow" if case.startswith("A_") else "Makeup_Flow"
            ax.plot(hold.time_min, hold[f"{dv}_true"], color="#222222", lw=1.1, label="True DV")
            ax.plot(hold.time_min, hold[f"{dv}_measured"], color="#0072B2", lw=.9, ls="--", label="Measured DV")
            ax.set_ylabel("DV deviation")
        ax.set_title(f"({chr(97 + col)}) {CASES[case]['label']}", fontsize=9)
        if col == 0:
            ax.legend(handles=dv_legend, frameon=False, fontsize=6.3, loc="upper right")
        elif col == 2:
            ax.legend(handles=unmeasured_legend, frameon=False, fontsize=6.0, loc="upper left")
        ax = axes[1, col]
        for cv, label, ls in (("HP_pH", "HP pH", "-"), ("MP_pH", "IP pH", "--")):
            ax.plot(without.time_min, without[f"{cv}_true"] - base.YSP[base.CV_NAMES.index(cv)], color=without_color, lw=.9, ls=ls)
            ax.plot(hold.time_min, hold[f"{cv}_true"] - base.YSP[base.CV_NAMES.index(cv)], color="#D55E00", lw=.9, ls=ls)
        ax.set_ylabel("pH deviation")
        if col == 0:
            ax.legend(handles=ph_legend, frameon=False, fontsize=5.4, ncol=1, loc="upper left")
        ax = axes[2, col]
        for mv, label, ls in ((base.MV_NAMES[0], "u1", "-"), (base.MV_NAMES[1], "u2", "--")):
            ax.plot(without.time_min, without[mv], color=without_color, lw=.9, ls=ls)
            ax.plot(hold.time_min, hold[mv], color="#D55E00", lw=.9, ls=ls)
        ax.set_ylabel("Supervisory command deviation")
        ax.set_xlabel("Time (min)")
        if col == 0:
            ax.legend(handles=command_legend, frameon=False, fontsize=5.4, ncol=1, loc="lower left")
        for row in range(3): axes[row, col].axvline(T0, color="#222222", lw=.7, ls="--")
    fig.tight_layout()
    fig.savefig(OUT / f"{filename_stem}.png", dpi=350)
    fig.savefig(OUT / f"{filename_stem}.pdf")
    plt.close(fig)


def plot_statistics(stats: pd.DataFrame, filename_stem: str = "isolated_DV_event_statistics") -> None:
    selected = ["Total_event_pH_IAE", "HP_peak_deviation", "IP_peak_deviation", "Total_MV_TV_event"]
    labels = {"Total_event_pH_IAE": "Total pH event IAE", "HP_peak_deviation": "HP peak deviation", "IP_peak_deviation": "IP peak deviation", "Total_MV_TV_event": "Total MV TV"}
    order = list(CASES)
    fig, axes = plt.subplots(2, 2, figsize=(7.5, 5.4), sharey=True)
    axes = axes.ravel()
    markers = ["o", "s", "D"]
    panel_prefixes = ["(a)", "(b)", "(c)", "(d)"]
    for panel_prefix, ax, metric in zip(panel_prefixes, axes, selected):
        sub = stats[stats.metric == metric].set_index("case").reindex(order)
        y = np.arange(len(order))
        values = sub.relative_change_percent.to_numpy(float)
        lo = sub.bootstrap_CI_lower.to_numpy(float)
        hi = sub.bootstrap_CI_upper.to_numpy(float)
        # Convert CI of absolute paired difference to relative units using the
        # corresponding without-DV mean recovered from the scenario data.
        # The plot's points retain exact CSV values; intervals are computed below.
        relative_ci = []
        for i, case in enumerate(order):
            denom = pair_denominators[(case, metric)]
            relative_ci.extend([100 * lo[i] / denom, 100 * hi[i] / denom, values[i]])
        limit = max(0.5, max(abs(x) for x in relative_ci) * 1.16)
        # The first three error metrics have comparable percent units, so a
        # common range enables direct visual comparison without clipping CIs.
        ax.set_xlim((-8, 6) if metric != "Total_MV_TV_event" else (-limit, limit))
        ax.spines["left"].set_visible(False)
        ax.tick_params(axis="y", length=0)
        ax.axvline(0, color="#777777", lw=.8, zorder=0)
        for i, case in enumerate(order):
            denom = pair_denominators[(case, metric)]
            xlo, xhi = 100 * lo[i] / denom, 100 * hi[i] / denom
            ax.errorbar(values[i], i, xerr=[[values[i] - xlo], [xhi - values[i]]], fmt=markers[i],
                        color="#333333", capsize=2, ms=4.5)
        ax.set_title(f"{panel_prefix} {labels[metric]}", fontsize=8)
        ax.set_xlabel("")
        ax.set_yticks(y)
        ax.set_yticklabels([CASES[x]["label"].replace("-only", "") for x in order])
        ax.invert_yaxis()
    fig.supxlabel("Relative change of DMC-DV hold versus DMC-without-DV (%)", fontsize=8, y=.02)
    fig.tight_layout(rect=(0, .055, 1, 1))
    fig.savefig(OUT / f"{filename_stem}.png", dpi=350)
    fig.savefig(OUT / f"{filename_stem}.pdf")
    plt.close(fig)


def write_report(templates: Dict[str, Dict], stage: np.ndarray, metrics: pd.DataFrame, stats: pd.DataFrame, checks: pd.DataFrame) -> None:
    focus = stats[stats.metric.isin(["Total_event_pH_IAE", "HP_peak_deviation", "IP_peak_deviation", "Total_MV_TV_event"])]
    onset = metrics.pivot(index=["case", "scenario_id"], columns="controller", values=["MV1_response_onset_min", "MV2_response_onset_min"])
    lines = [
        "# Isolated disturbance-event analysis",
        "",
        "This offline theoretical experiment compares only DMC-without-DV and DMC-DV hold. Both use the same nominal model, P=40, M=5, Q, Ru, constraints, innovation correction, active-set QP, QP-failure/PID-fallback logic, sampling period, plant, mismatch, noise draws, and seed within every case/scenario pair.",
        "",
        "## Event template provenance",
        "",
        f"Scenario 7 was regenerated from saved seed {base.MASTER_SEED + 7}. Condensate-flow template: amplitude {templates['condensate']['amplitude']:.12f}, {templates['condensate']['kind']}, {templates['condensate']['duration_min']} min. Makeup-flow template: amplitude {templates['makeup']['amplitude']:.12f}, {templates['makeup']['kind']}, {templates['makeup']['duration_min']} min. The 26-min coloured unmeasured event was reconstructed exactly from the generator seed; its saved Euclidean norm is {templates['unmeasured']['amplitude']:.12f} and vector is [{', '.join(f'{x:.12f}' for x in stage)}]. Each template is shifted to t0=180 min without accessing future values in control.",
        "",
        "## Sanity checks",
        "",
        f"All {len(checks)} controller trajectories passed the DV-path checks. In A only condensate-flow event is present; in B only makeup-flow event is present; in C no measured-DV event is present. Background AR(1) disturbance is retained only in Level 2.",
        "",
        "## Paired stochastic results",
        "",
        "Signed differences and relative changes are DMC-DV hold minus DMC-without-DV. For error metrics, negative values favor hold. Recovery time is right-censored (blank) if no 10-min sustained ±0.005 pH recovery occurs in the predeclared [160, 280] min window; statistics use only observed matched pairs and state n_paired in the CSV.",
        "",
        focus.to_csv(index=False),
        "",
        "## Early-response diagnostic",
        "",
        "The early window is [180, 185] min. It is retained because the nominal related DV-to-CV delays are 3-4 min. MV onset uses the predeclared 10% of the actual 0.03/min rate limit (0.003/min) threshold and is supplementary only.",
        "",
        "## Interpretation boundary",
        "",
        "No result was tuned or changed to meet an expected direction. QP failures and DMC-active ratios are reported in scenario-level output; any Case C difference must be interpreted as incidental DV-noise/control-path effects rather than preview of the unmeasured event.",
        "",
        "## Suggested manuscript addition (do not apply automatically)",
        "",
        "Add a short Section 5.3 companion paragraph that distinguishes the existing 30-scenario aggregate DV ablation (overall average benefit) from this isolated-event experiment (mechanism). Cite the clean trajectories for timing of the measured-DV response, the paired Level-2 event-window estimates for uncertainty, and Case C as the negative control. Do not present the clean trajectory as inferential evidence.",
    ]
    (OUT / "isolated_disturbance_report.md").write_text("\n".join(lines), encoding="utf-8")


pair_denominators: Dict[Tuple[str, str], float] = {}


def main() -> None:
    global pair_denominators
    manifest = json.loads((SOURCE_OUT / "simulation_manifest.json").read_text(encoding="utf-8"))
    if manifest["P"] != 40 or manifest["M"] != 5:
        raise RuntimeError("Existing baseline manifest does not contain the fixed P=40, M=5 controller")
    base.configure_horizon(40)
    pidpars = manifest["PID_parameters"]
    _source, templates, source_stage = _source_events()
    template_rows = []
    for key in ("condensate", "makeup"):
        arr = _shifted_dv_template(templates[key])
        for k in range(T):
            template_rows.append({"case": key, "time_min": k, "source_scenario_id": 7, "source_start_min": templates[key]["start_min"], "analysis_start_min": T0, "waveform_value": arr[k, templates[key]["dv_index"]]})
    for k in range(T):
        template_rows.append({"case": "unmeasured", "time_min": k, "source_scenario_id": 7, "source_start_min": templates["unmeasured"]["start_min"], "analysis_start_min": T0, "waveform_value": float(np.linalg.norm(source_stage)) if T0 <= k < T0 + templates["unmeasured"]["duration_min"] else 0.0})
    pd.DataFrame(template_rows).to_csv(OUT / "isolated_disturbance_event_templates.csv", index=False)

    frames, metric_rows = [], []
    for case in CASES:
        for level, ids in (("clean", (0,)), ("stochastic", TEST_IDS)):
            for sid in ids:
                scn = make_isolated_scenario(case, sid, level, templates, source_stage)
                for controller in (WITHOUT, HOLD):
                    frame = run_controller(scn, controller, pidpars, case, level)
                    frames.append(frame)
                    metric_rows.append(event_metrics(frame))
    timeseries = pd.concat(frames, ignore_index=True)
    metrics = pd.DataFrame(metric_rows)
    checks = sanity_checks(timeseries)
    audit = pairing_audit(timeseries)
    stochastic = metrics[metrics.level == "stochastic"].copy()
    clean_metrics = metrics[metrics.level == "clean"].copy()
    stats = paired_statistics(stochastic)
    summary = summary_table(stochastic)
    pair_denominators = {(case, metric): float(group[group.controller == WITHOUT][metric].mean()) for case, group in stochastic.groupby("case") for metric in ["Total_event_pH_IAE", "HP_peak_deviation", "IP_peak_deviation", "Total_MV_TV_event"]}

    timeseries.to_csv(OUT / "isolated_disturbance_timeseries.csv", index=False)
    clean_metrics.to_csv(OUT / "isolated_disturbance_clean_metrics.csv", index=False)
    stochastic.to_csv(OUT / "isolated_disturbance_scenario_level.csv", index=False)
    summary.to_csv(OUT / "isolated_disturbance_summary.csv", index=False)
    stats.to_csv(OUT / "isolated_disturbance_pairwise_statistics.csv", index=False)
    checks.to_csv(OUT / "isolated_disturbance_sanity_checks.csv", index=False)
    audit.to_csv(OUT / "isolated_disturbance_pairing_audit.csv", index=False)
    plot_response(timeseries[timeseries.level == "clean"])
    plot_statistics(stats)
    write_report(templates, source_stage, stochastic, stats, checks)
    manifest_out = {
        "analysis": "isolated single disturbance-event DV information experiment",
        "source_template": "scenario_id=7 regenerated from saved seed and existing event generator",
        "t0_min": T0, "duration_min": T, "event_window_min": [WINDOW_START, WINDOW_END], "early_window_min": [T0, EARLY_END],
        "levels": {"clean": "nominal, no measurement noise, no AR(1) background", "stochastic": "30 matched scenario_id=1..30 with existing mismatch, noises, and AR(1) background"},
        "controllers": {WITHOUT: "d_ctrl=d_hat=0 and nominal model advances with zero DV", HOLD: "d_ctrl=d_meas and P-step zero-order hold"},
        "bootstrap": "10000 paired percentile resamples; hold minus without-DV", "no_retuning": True,
    }
    (OUT / "isolated_disturbance_manifest.json").write_text(json.dumps(manifest_out, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps({"output_dir": str(OUT), "stochastic_rows": len(stochastic), "statistics_rows": len(stats), "sanity_checks": len(checks)}, ensure_ascii=False))


if __name__ == "__main__":
    main()
